FROM php:7.4.33-fpm as base

ARG UID=1000
RUN adduser deploy --disabled-password --home /home/deploy --uid $UID

RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
    apt-get install -y docker.io

RUN usermod -aG docker deploy

RUN apt-get update && apt-get install -y default-mysql-client \
    && apt-get install -y postgresql-client \
    && apt-get install -y wget \
    && apt-get install -y libxml2-dev \
    && apt-get install -y unzip

RUN apt-get update && apt-get install -y \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    && apt-get install -y libxslt-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    #&& docker-php-ext-install -j$(nproc) opcache \
    && docker-php-ext-install -j$(nproc) zip \
    && docker-php-ext-install -j$(nproc) soap \
    && docker-php-ext-install -j$(nproc) xsl \
    && docker-php-ext-install -j$(nproc) pdo_mysql

RUN pecl install redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install bcmath && docker-php-ext-enable bcmath
RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap

ARG COMPOSER_VERSION=2.5.8

RUN wget -O /usr/bin/composer https://github.com/composer/composer/releases/download/$COMPOSER_VERSION/composer.phar && \
    chmod +x /usr/bin/composer

FROM base as dev
#COPY --chown=root:root /infrastructure/php/development/ext/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

ARG NODE_VERSION=16

RUN mkdir -p /etc/apt/keyrings && apt-get update && apt-get install -y ca-certificates curl gnupg \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update && apt-get install -y nodejs

RUN usermod -aG docker deploy

USER deploy

RUN composer global require laravel/vapor-cli --update-with-dependencies

ENV PATH="/home/deploy/.config/composer/vendor/bin:${PATH}"

FROM dev as build

RUN mkdir -p /build

RUN chown -R deploy:deploy /build

RUN usermod -aG docker deploy

USER deploy

COPY --chown=deploy:deploy ./package.json ./package-lock.json /build/
COPY --chown=deploy:deploy ./tailwind.config.js /build/
COPY --chown=deploy:deploy ./composer.json ./composer.lock ./artisan /build/
COPY --chown=deploy:deploy ./public  /build/public
COPY --chown=deploy:deploy ./resources  /build/resources

WORKDIR /build

RUN npm install

RUN composer install --no-scripts

RUN npm run build

USER root

FROM base as prod


COPY --chown=deploy:deploy . /home/deploy/laravel

#COPY --chown=deploy:deploy ./composer.json ./artisan /home/deploy/laravel/
#COPY --chown=root:root /infrastructure/php/production/ext/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

COPY --chown=deploy:deploy --from=build /build/public/build /home/deploy/laravel/public/build
#COPY --chown=deploy:deploy --from=build /build/vendor /home/deploy/laravel/vendor
#COPY --chown=deploy:deploy --from=build /build/node_modules /home/deploy/laravel/node_modules


#RUN export PATH="$PATH:/root/.config/composer/vendor/laravel/vapor-cli"

RUN usermod -aG docker deploy

USER deploy

EXPOSE 9000
