upstream app-upstream {
    server app:9000;
}

server {
    listen 80;
    listen [::]:80;
    http2  on;

    server_name sii-services.test *.sii-services.test;
    #server_name localhost; # Agrega esta línea si quieres usar localhost
    root   /home/deploy/laravel/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location / {
        rewrite ^ /index.php last;
    }

    location /build/ {
        #root /app/public;
        root /home/deploy/laravel/public;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app-upstream;
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

